---
title: Crash Course in Git, Quarto, and R
author: 
  - name: Dillon Labonte
    email: dillon.labonte@snhu.edu
    affiliations: 
      - name: Southern New Hampshire University
format: html
date: 1/8/2025
date-modified: today
date-format: long
theme: flatly
toc: true
code-fold: true
warning: false
message: false
---

## Working with Data

```{r}

library(tidyverse)
library(kableExtra)

# styling
options(kable_styling_bootstrap_options = c("hover", "striped"))
theme_set(theme_bw(base_size = 14))

# read in hits data
hits <- read_csv("https://raw.githubusercontent.com/agmath/agmath.github.io/refs/heads/master/data/classification/battedballs.csv")

# read in parks data
parks <- read_csv("https://raw.githubusercontent.com/agmath/agmath.github.io/refs/heads/master/data/classification/park_dimensions.csv")

```

## Exploring Our Data

```{r}

hits |>
  head() |>
  kable() |>
  kable_styling()

```

```{r}

parks |>
  head() |>
  kable() |>
  kable_styling()

```

## Joining the Data

```{r}

hits <- hits |>
  left_join(parks, by = c("park" = "park"))

```

